export * from './userRoute';
export * from './roleRoute';
export * from './userRoute';
export * from './salleRoute';
export * from './equipmentRoute';
export * from './exerciceRoute';
export * from './progressionRoute';
export * from './challengeRoute';
export * from './rewardRoute';
export * from './badgeRoute';
export * from './groupChallengeRoute';
export * from './participationRoute'